CLIENT-2145
aerospike/aerospike-client-nodejs pull request #504
Opened 2023-01-24 14:54 UTC by DomPeliniAerospike

2023-02-02 20:05 UTC, justinlee-aerospike requested changes
Generally looks good.  I'll approve after making the two discussed changes and also verifying that the typings specified in index.d.ts work for Typescript.

2023-02-03 16:39 UTC, DomPeliniAerospike commented on scripts/prebuiltBinding.js
> +          fs.rename('lib/binding/openssl@3/node-v111-linux-x64', 'lib/binding/node-v111-linux-x64', (err) => {
This is covered in my recent commit: https://github.com/aerospike/aerospike-client-nodejs/pull/504/commits/014cd8448ce3f7000adfb8fc1cdef5eebbdf2f48 
Resolving now.

2023-02-03 16:40 UTC, DomPeliniAerospike commented on test/batch_write.js
> +          key: new Key(helper.namespace, helper.set, 'test/batch_write/2'),
This is covered in my recent commit: https://github.com/aerospike/aerospike-client-nodejs/pull/504/commits/014cd8448ce3f7000adfb8fc1cdef5eebbdf2f48 
Resolving now.

2023-02-03 16:40 UTC, DomPeliniAerospike commented on src/main/cdt_ctx.cc
> +{
This is covered in my recent commit: https://github.com/aerospike/aerospike-client-nodejs/pull/504/commits/014cd8448ce3f7000adfb8fc1cdef5eebbdf2f48 
Resolving now.

2023-02-03 23:23 UTC, justinlee-aerospike approved these changes
changes look good

2023-02-03 23:54 UTC, artanderson approved these changes
Haven’t had the chance to test, but the changes look good to me.

2023-02-07 20:20 UTC, justinlee-aerospike approved these changes
changes look good.  eslint doesn't seem to do the formatting well.  Let's look into using prettier to format in the future.

2023-02-07 21:37 UTC, merged